#---- GENERAL
GPU: 0
VERBOSE: False

#---- PATHS
MODEL_DIR: 'bin/'
RESULTS_DIR: 'results/'
LOG_DIR: 'logs/'
MODEL_NAME: 'AcT'
X_TRAIN: "X.txt"
Y_TRAIN: "Y.txt"
X_TEST: "X_test.txt"
Y_TEST: "Y_test.txt"

#---- DATASET
SPLITS: 3
FOLDS: 10
SEEDS: [11331, 11435, 12123, 53453, 42344, 24234, 65747, 84443, 29345, 99543]
VAL_SIZE: 0.1
CHANNELS: 4
SUBSAMPLE: 1
LEGACY: False
KEYPOINTS: 17
CLASSES: 22
FRAMES: 32
LABELS : [
  "russian twist",
  "tricep dips",
  "t bar row",
  "squat",
  "shoulder press",
  "romanian deadlift",
  "push-up",
  "plank",
  "leg extension",
  "leg raises",
  "lat pulldown",
  "incline bench press",
  "tricep pushdown",
  "pull up",
  "lateral raise",
  "hammer curl",
  "decline bench press",
  "hip thrust",
  "bench press",
  "chest fly machine",
  "deadlift",
  "barbell biceps curl"
]

#---- MODEL
#PATCH_SIZE: 1
MODEL_SIZE: 'micro'
POS_EMB: #'utils/pos_emb.npy'
micro:        
    N_HEADS: 1
    N_LAYERS: 4
    EMBED_DIM: 64
    DROPOUT: 0.3
    MLP: 256


#---- TRAINING SETTINGS 
N_EPOCHS: 350       
BATCH_SIZE: 512

